name: Latest Blog Post

on:
  schedule:
    # Run at 00:00 on Monday
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Main Blog Source
        id: main_blog
        continue-on-error: true
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://blog.liansifan.me/rss.xml,https://blog.liansifan.me/atom.xml"
          max_post_count: 5
          template: "$newline- [$title]($url)"

      - name: Backup Blog Source
        if: steps.main_blog.outcome == 'failure'
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://fans-docs.pages.dev/rss.xml"
          max_post_count: 5
          template: "$newline- [$title]($url)"
